version: '3.8'

services:
  db:
    image: postgres
    container_name: db_report
    env_file:
      - .env
    ports:
      - 5436:5432

  redis:
    image: redis:alpine
    ports:
      - 6379:6379